### ISSUE TITLE
fof/impersonate 1.0.0 requires flarum/core ^1.0.0

### ISSUE THREAD

**Issue by sibidharan** [flagrow/impersonate#21]
When I try to install using the recommended steps, I get this error

```
fof/impersonate 1.0.0 requires flarum/core ^1.0.0 -> found flarum/core[dev-master, 1.x-dev (alias of dev-master)] but it does not match your minimum-stability.
```

**Comment by imorland** [comment]
Erm, yes? 

This extension has just been updated ahead of the upcoming Flarum 1.0 release. It won't be installable yet, and this is expected.

**Comment by clarkwinkelmann** [comment]
To install the extension on Flarum beta 16, make sure you use the command `composer require fof/impersonate:*` (with the `:*` at the end)

We still have references to the old command lying around, we will update them as soon as possible. Using the old command will indeed try to install the very latest version of the extension which is only for the upcoming Flarum 1.x release.
